### PR TITLE
Allow opening JupyterCAD documents with the JSON viewer + Allow opening STL and STEP in JupyterLite

### PR DESCRIPTION
**Pull request by martinRenou**
Fix https://github.com/jupytercad/JupyterCAD/issues/454

Screenshot from 2024-10-23 14-58-14

### CODE REVIEW

**Review by SylvainCorlay — APPROVED** [review]

**Comment by arjxn-py** [comment]
Bot please update snapshots 🫤

**Comment by martinRenou** [comment]
There seems to be a real issue with other file types like stl and step that can't be open anymore

**Comment by martinRenou** [comment]
Latest commit makes it work with the jupytercad app

Screenshot from 2024-10-23 16-40-52

**Comment by martinRenou** [comment]
nope

**Comment by martinRenou** [comment]
Finally 🚀 Opening STL files in JupyterLite works now. Will apply the same changes on STEP and fix the CI later.

Screenshot from 2024-10-23 19-12-35

**Comment by martinRenou** [comment]
The CI failures are jupyter-collaboration related. Let's get this PR on hold while collaboration gets properly fixed.

e.g. https://github.com/jupyterlab/jupyter-collaboration/pull/383

**Review by trungleduc — APPROVED** [review]

**Comment by SylvainCorlay** [comment]
This is looking great!

**Pull request merged**
