### PR TITLE
Some clip plane improvements

### PR DESCRIPTION
**Pull request by martinRenou**
Explore fixing #500 + explore fixing z-fighting using polygon offset. 

I can't seem to implement the later using the logarithmic depth buffer, so opening as draft for now.

https://github.com/user-attachments/assets/aef66c27-0bec-4e5c-b275-ce086f6552cf

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Maybe the simpler color theme fix could be merged independently first.

**Comment by martinRenou** [comment]
This may be a bit more involved as this will require hacking around the fragment shader to manually offset the depth computation after the logarithmic depth buffer was performed. See #509

**Comment by SylvainCorlay** [comment]
I think that the clip plane remains a case in which solving the z fighting issue makes a lot of sense.

**Comment by martinRenou** [comment]
Definitely

**Comment by martinRenou** [comment]
Replaced by https://github.com/jupytercad/JupyterCAD/pull/539

**Pull request closed without merging**
