### PR TITLE
Orthographic camera: fix missing near and far parameters

### PR DESCRIPTION
**Pull request by martinRenou**
This fixes visual artifacts issues when rendering big/small objects with the orthographic camera

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Should one revert some of https://github.com/jupytercad/JupyterCAD/pull/492

**Comment by martinRenou** [comment]
What do you mean?

**Comment by SylvainCorlay** [comment]
>  What do you mean?

Ah, I thought it was related to zoom level.

**Comment by martinRenou** [comment]
Not at all, these are the camera depth check limits

**Pull request merged**
