### PR TITLE
Reorder toolbar icons

### LINKED ISSUE #518: Reorder toolbar buttons
The last toolbar buttons are ordered in a way that is not very intuitive to me:

Image

I believe we should reorder them in:
- Exploded view
- Clip plane
- Wireframe
- SEPARATOR
- Axes
- Camera
- SEPARATOR
- Console

That way we separate the buttons that have an impact on the shapes themselves from the "view" buttons, and the console is alone.

### PR DESCRIPTION
**Pull request by arjxn-py**
image

Shall close #518

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
bot please update snapshots

**Comment by arjxn-py** [comment]
Bot please update snapshots

**Comment by arjxn-py** [comment]
> From the screenshot I realize the separators are not displayed when the toolbar is collapsed under `...`.

yeah right, nice catch 🎣

**Pull request merged**
