### PR TITLE
Update jupyter-collaboration v3.0.0-beta.8

### LINKED ISSUE #471: RTC is broken on the main branch
With the latest changes in `jupyter-collaboration`, the RTC features do not work anymore, which causes failed UI tests.

### PR DESCRIPTION
**Pull request by davidbrochart**
Closes #471.

[yjs-widgets](https://github.com/QuantStack/yjs-widgets) will also have to use jupyter-collaboration v3.

### CODE REVIEW

**Comment by davidbrochart** [comment]
> [yjs-widgets](https://github.com/QuantStack/yjs-widgets) will also have to use jupyter-collaboration v3.

Maybe this is the cause of the failures?

**Comment by trungleduc** [comment]
```bash
  Type 'JupyterCadDoc' is missing the following properties from type 'YDocument<DocumentChange>': source, getSource, setSource
src/stepplugin/plugins.ts(61,9): error TS2322: Type '() => JupyterCadStepDoc' is not assignable to type 'SharedDocumentFactory'.
  Type 'JupyterCadStepDoc' is missing the following properties from type 'YDocument<DocumentChange>': source, getSource, setSource
src/stlplugin/plugins.ts(61,9): error TS2322: Type '() => JupyterCadStlDoc' is not assignable to type 'SharedDocumentFactory'.
  Type 'JupyterCadStlDoc' is missing the following properties from type 'YDocument<DocumentChange>': source, getSource, setSource
```

**Comment by davidbrochart** [comment]
Yes, see https://github.com/jupyter-server/jupyter_ydoc/pull/273.

**Comment by trungleduc** [comment]
> > [yjs-widgets](https://github.com/QuantStack/yjs-widgets) will also have to use jupyter-collaboration v3.
> 
> Maybe this is the cause of the failures?

you can add `"@jupyter/collaboration:^3.0.0-beta.8"` to the `resolutions` field of root package's `package.json` to force using only one version

**Pull request merged**
