### PR TITLE
Object properties panel: Use selected object name as the title

### PR DESCRIPTION
**Pull request by martinRenou**
Fix https://github.com/jupytercad/JupyterCAD/issues/477
Closes https://github.com/jupytercad/JupyterCAD/issues/543

https://github.com/user-attachments/assets/b85dedbe-c056-478e-8ea1-4181b500f6f8

https://github.com/user-attachments/assets/b177e44a-291e-44d2-b0fa-feb343afd1e6

### CODE REVIEW

**Comment by martinRenou** [comment]
Completely empty, as in removing the "object properties" title?

Screenshot from 2024-10-25 16-48-55

**Comment by SylvainCorlay** [comment]
Yes, or even like in the standard panel.

Screenshot 2024-10-25 at 16 56 40

**Comment by SylvainCorlay** [comment]
The current behavior is that you can still edit the properties of the last thing that was selected, which may be misleading.

**Comment by trungleduc** [comment]
Clicking on other documents removes the form but still keeps the object name.

cad22

**Comment by SylvainCorlay** [comment]
I think it is a clear improvement over the current state. I would be super keen on integrating it as it stands.

**Comment by martinRenou** [comment]
I marked the PR as ready to review again. Although trung's comment may be an actual bug of my implementation

**Comment by trungleduc** [comment]
Bot please update snapshots!

**Review by trungleduc — APPROVED** [review]

**Pull request merged**
