### PR TITLE
Add clipping plane and exploded view icons

### PR DESCRIPTION
**Pull request by IsabelParedes**
Inspo:

Icons:

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
For the clipping plane, how about making the clipping plane a bit larger and removing the back of the cube?

376754771-1f822ead-26db-4d37-8afe-017f5e029736

**Comment by trungleduc** [comment]
Thanks @IsabelParedes. I pushed an update to get the preview link.

**Comment by SylvainCorlay** [comment]
A new version closer to the original, with square angles on the cut part of the cube.

Original:

clipping

Png:

cube

**Comment by arjxn-py** [comment]
376816413-b7a93e91-aa2a-4f86-a040-6f04ddb77f60 1

Thanks @SylvainCorlay, Here's an SVG for the same :)

**Comment by SylvainCorlay** [comment]
Ah yes, the first attachment that appeared very small was already an svg.

**Comment by arjxn-py** [comment]
> Ah yes, the first attachment that appeared very small was already an svg.

Oh oops, my bad 😅

**Comment by IsabelParedes** [comment]
Thanks for all the feedback! 

image

image

**Review by martinRenou — APPROVED** [review]
Thanks!!

**Pull request merged**
