### PR TITLE
Add test for rotated shape

### PR DESCRIPTION
**Pull request by arjxn-py**
Related to #580

### CODE REVIEW

**Comment by arjxn-py** [comment]
Please update snapshots.

**Comment by arjxn-py** [comment]
Galata workflow failing https://github.com/jupytercad/JupyterCAD/actions/runs/11912035179/job/33194795551?pr=583#step:7:33 😕

**Comment by martinRenou** [comment]
> Galata workflow failing

The galata workflow requires the build artifacts to be published before it can run, maybe that build was not done yet https://github.com/jupytercad/JupyterCAD/actions/runs/11911814236/job/33194119583?pr=583

I restarted the galata workflow

**Comment by arjxn-py** [comment]
Please update snapshots

**Comment by martinRenou** [comment]
Closing and reopening to trigger CI

**Pull request merged**
