### PR TITLE
Add stl and stp icons

### LINKED ISSUE #535: STL and STEP file icons
It seems that the file icon is not showing up in the tab title for STL and STEP files.

On a separate note, it would probably make sense to not use the JupyterCAD logo for these file types, but use a different one for each.

### PR DESCRIPTION
**Pull request by IsabelParedes**
Resolves #535

### CODE REVIEW

**Comment by martinRenou** [comment]
This is how it looks in practice:

Screenshot From 2024-11-28 12-53-49
Screenshot From 2024-11-28 12-53-57

**Comment by SylvainCorlay** [comment]
Awesome!

I think that what is missing is the coloring of the icon in white when the item is selected in the file browser.

Screenshot 2024-11-28 at 13 18 42

Screenshot 2024-11-28 at 13 18 36

Screenshot 2024-11-28 at 13 18 28

**Comment by SylvainCorlay** [comment]
It seems that the icon is missing from the tab handle.

**Comment by martinRenou** [comment]
Both mentioned issues should be fixed now 🚀

**Review by SylvainCorlay — APPROVED** [review]

**Pull request merged**
