### PR TITLE
Update example for colors

### PR DESCRIPTION
**Pull request by arjxn-py**
These are auto-updated changes through jcad editor.

### CODE REVIEW

**Comment by arjxn-py** [comment]
Bot please update snapshots.

**Comment by arjxn-py** [comment]
[Update Galata References](https://github.com/jupytercad/JupyterCAD/actions/runs/11011665716) is failing

**Comment by arjxn-py** [comment]
Bot please update snapshots.

🎬 Take 2

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
