### PR TITLE
Step file export to .jcad

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
It seems I cannot open the resulting exported file and getting the dreaded:

```
if event == "metadata" and self._last_modified < args["last_modified"]:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

which [should have been fixed in jupyter_collaboration 2.0.0](https://github.com/jupyterlab/jupyter-collaboration/issues/162)

**Comment by trungleduc** [comment]
Everytime I have this error message, the real error is from my code and not from `jupyter_collaboration`

**Comment by martinRenou** [comment]
> Everytime I have this error message, the real error is from my code and not from jupyter_collaboration

It seems that the latest jupyter-collaboration 1.x patch does not hide the real error anymore with this last_modified thingy.

**Comment by martinRenou** [comment]
please update snapshots

**Comment by martinRenou** [comment]
please update snapshots

**Comment by martinRenou** [comment]
https://github.com/jupytercad/jupytercad/actions/runs/7842797150

**Pull request merged**
