### PR TITLE
Fix python console in the standalone app

### LINKED ISSUE #399: BUG: Error when Running JupyterCAD through `jupyter cad` Command
When running JupyterCAD through the `jupyter cad` command in the terminal, the following errors are encountered in the browser logs, and the JupyterCAD editor fails to open:

```
Error: Shared module @jupyterlab/codeeditor doesn't exist in shared scope default
```
```
Error: Shared module @jupyterlab/completer doesn't exist in shared scope default
```
However, this issue does not occur when JupyterCAD is accessed through the `jupyter lab` command. In that case, the editor opens successfully without any errors.

### PR DESCRIPTION
**Pull request by trungleduc**
- Add missing tokens to make python console work in the standalone app
- Closes #399
- Needs https://github.com/QuantStack/yjs-widgets/pull/14

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Thanks!

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by arjxn-py** [comment]
Thanks @trungleduc, I got a bit late on picking #399 up 😄

**Comment by trungleduc** [comment]
> Thanks @trungleduc, I got a bit late on picking #399 up 😄

don't worry, it is more complicated than it sounds

**Pull request merged**
