### PR TITLE
Bump jupyter-collaboration v3

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
[Failures](https://github.com/jupytercad/JupyterCAD/actions/runs/10917477913/job/30301157626?pr=429) seem to be relevant?

**Comment by trungleduc** [comment]
> [Failures](https://github.com/jupytercad/JupyterCAD/actions/runs/10917477913/job/30301157626?pr=429) seem to be relevant?

yes, are you able to add new object to the JCAD file?

**Comment by davidbrochart** [comment]
Yes.

**Comment by trungleduc** [comment]
Bumping Galata to the latest version might help

**Comment by trungleduc** [comment]
We need another pass on the UI test with the new Galata version. I'll work on it

**Comment by trungleduc** [comment]
@davidbrochart it's green now

**Comment by davidbrochart** [comment]
Nice, thanks!
Do you think we should merge it, or make a final release of `jupyter-collaboration` v3?

**Comment by trungleduc** [comment]
I don't know about releasing jupyter-collaboration but i have no issue merging this PR.

**Comment by davidbrochart** [comment]
Yes I think we can merge in either case :+1:

**Review by trungleduc — APPROVED** [review]

**Pull request merged**
